name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Build and push Docker image
        run: |
          # Set your Docker image tag (can be based on commit hash or version)
          IMAGE_TAG=gcr.io/${{ secrets.GCP_PROJECT_ID }}/deployment-demo:$GITHUB_SHA
          
          # Build the Docker image
          docker build -t $IMAGE_TAG .
          
          # Authenticate Docker with GCR
          gcloud auth configure-docker --quiet
          
          # Push Docker image to GCR
          docker push $IMAGE_TAG

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy deployment-demo \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/deployment-demo:$GITHUB_SHA \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars DB_URL=${{ secrets.DB_URL }},DB_USERNAME=${{ secrets.DB_USERNAME }},DB_PASSWORD=${{ secrets.DB_PASSWORD }}

      - name: Notify success
        run: echo "Successfully deployed to Google Cloud Run!"
