name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Build JAR using Maven
        run: mvn clean package -DskipTests

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=us-central1-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT }}/cloud-run-source-deploy/deployment-demo:$GITHUB_SHA
          docker build -t $IMAGE_TAG .
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
          docker push $IMAGE_TAG

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy deployment-demo \
            --timeout 600s
            --image us-central1-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT }}/cloud-run-source-deploy/deployment-demo:$GITHUB_SHA \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars DB_URL=${{ secrets.DB_URL }},DB_USERNAME=${{ secrets.DB_USERNAME }},DB_PASSWORD=${{ secrets.DB_PASSWORD }}

      - name: Notify success
        run: echo "Successfully deployed to Google Cloud Run!"
